### ISSUE TITLE
Where is the self-attentive logic

### ISSUE THREAD

**Issue by Vichoko** [kaushalshetty/Structured-Self-Attention#11]
i could not find the self-attention encoder. I found a LSTM that encodes the embeddings, but nothing else.

**Comment by kaushalshetty** [comment]
https://github.com/kaushalshetty/Structured-Self-Attention/blob/84ed64f9cee75f84a5d871a46508a308182e4a6d/attention/model.py#L107

There is no self attention encoder. Self attention is been implemented  as an operation on the LSTM outputs
