### ISSUE TITLE
penalizing term

### ISSUE THREAD

**Issue by rshivansh** [kaushalshetty/Structured-Self-Attention#3]
Hi thanks for the code;

whats the value of penalizing coefficient for frobenius norm.
Thanks

**Comment by rshivansh** [comment]
while calculating the loss of penalizing term 
what do we have to divide the penal value with in - C * ( penal / X  )
what is X in this case?

thanks

**Comment by kaushalshetty** [comment]
@rshivansh 
X is the batch size. The penalisation is summed up across all samples in your batch and hence it is necessary to normalise (divide) by the size of the batch.
