### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by heukirne** [kaushalshetty/Structured-Self-Attention#6]
Hello dear @kaushalshetty ,

I'm trying to run your experiments, but I can get the same results.
I made the same changes than [webdizz](https://github.com/webdizz/Structured-Self-Attention/commit/c58350b39a97e0aaa4579b90ba0e65fdbb0b33a9), but the accuracy are always 50%.
This default configuration should generate the 93.4% accuracy result?

Thanks

**Comment by kaushalshetty** [comment]
Sorry @heukirne , I am not maintaining the repo anymore but I just re-ran the code and I see the claimed results with pytorch 0.3. I did not test it for pytorch>0.3 .

**Comment by heukirne** [comment]
Ok, @kaushalshetty, thanks!
